---
scenario_start_time: 130
country: victoria
iso3: VIC

implement_importation: True
imported_cases_explict: False

infectious_seed: 0

start_time: 15.
end_time: 365.

contact_rate: 0.024
non_sympt_infect_multiplier: .464939

young_reduced_susceptibility: .4484674
prop_detected_among_symptomatic: .8035
npi_effectiveness:
  other_locations: .9697829

self_isolation_effect: .434371
enforced_isolation_effect: .9858

mixing:
  other_locations_times:
    [
      72,
      73,
      74,
      75,
      76,
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88,
      89,
      90,
      91,
      92,
      93,
    ]
  other_locations_values:
    [
      1.,
      .95,
      .89,
      .81,
      .79,
      .66,
      .53,
      .50,
      .49,
      .46,
      .42,
      .33,
      .25,
      .20,
      .20,
      .18,
      .18,
      .18,
      .18,
      .15,
      .15,
      .14,
    ]
  work_times:
    - 78.
    - 79.
    - 81.
    - 82.
    - 84.
    - 85.
    - 86.
    - 87.
    - 91.
    - 92.
  work_values:
    - 1.
    - 0.95
    - 0.95
    - 0.9
    - 0.9
    - 0.7
    - 0.7
    - 0.5
    - 0.5
    - 0.25
  school_times:
    - 84.
    - 85.
  school_values:
    - 1.
    - 0.

data:
  times_imported_cases: [70., 71., 86., 100., 107]
  n_imported_cases: [1, 1, 45, 4, 1.1341]
