iso3: GBR

#start_time: -20.
end_time: 360.
scenario_start_time: 182

infectious_seed: 200
use_verity_mortality_estimates: False

# MLE estimates
contact_rate: 0.04484913212752213
start_time: 14.743091717239954
npi_effectiveness:
  other_locations: 0.7277700900816946
compartment_periods_calculated:
  incubation:
    total_period: 4.795574675158399
  total_infectious:
    total_period: 5.21461782400086
tv_detection_b: 0.08578716018273512
tv_detection_c: 87.69865201709473
prop_detected_among_symptomatic: 0.5306999105838264
icu_prop: 0.18442172255181138
ifr_double_exp_model_params:
  k: 9.058014703803742
  last_representative_age: 80.12116425290792
compartment_periods:
  hospital_late: 8.901251451337675
  icu_late: 9.251236688037917
notifications_dispersion_param: 1.7936013947450073
infection_deathsXall_dispersion_param: 0.8917230289189196

microdistancing:
  b: -0.05
  c: 115.16320008339129  # MLE
  sigma: 0.6128211731293335  # MLE

mixing:
  school:
    append: false
    times:
      - 2020-03-18
      - 2020-03-20
      - 2020-06-27
    values:
      - 1.0
      - 0.1
      - 0.1

# Mapping of Google Mobility locations to Autumn-specific locations
google_mobility_locations:
  work:
    - workplaces
  other_locations:
    # Parks not included
    - retail_and_recreation
    - grocery_and_pharmacy
    - transit_stations
