iso3: BEL

#start_time: -20.
end_time: 214.
scenario_start_time: 213

infectious_seed: 200
use_verity_mortality_estimates: True

microdistancing:
  b: -0.05
  c: 108.55252612086493 # MLE
  sigma: 0.6535086122143022  # MLE

hospital_props_multiplier: .5

# MLE estimates
contact_rate: 0.05919319201817061
start_time: 39.611930675726306
npi_effectiveness:
  other_locations: 0.9619422398740342
compartment_periods_calculated:
  incubation:
    total_period: 2.760531650438542
  total_infectious:
    total_period: 4.4957542453434
tv_detection_b: 0.08341963086831532
tv_detection_c: 117.46010912326226
prop_detected_among_symptomatic: 0.1017844994449625
icu_prop: 0.24371306627152672
compartment_periods:
  hospital_late: 13.13979106597376
  icu_late: 8.861981683941238
hospital_props_multiplier: 0.3730189453021552

mixing:
  school:
    append: false
    times:
      - 2020-03-12
      - 2020-03-13
      - 2020-07-30
    values:
      - 1.0
      - 0.1
      - 0.1

# Mapping of Google Mobility locations to Autumn-specific locations
google_mobility_locations:
  work:
    - workplaces
  other_locations:
    # Parks not included
    - retail_and_recreation
    - grocery_and_pharmacy
    - transit_stations
