iso3: BEL

#start_time: -20.
end_time: 190.
scenario_start_time: 182

infectious_seed: 200
use_verity_mortality_estimates: False

microdistancing:
  b: -0.05
  c: 99.27164890127986 # MLE
  sigma: 0.6688860622737479  # MLE

# MLE estimates
contact_rate: 0.05140657234427222
start_time: 32.33193809731787
npi_effectiveness:
  other_locations: 0.7997335187280273
compartment_periods_calculated:
  incubation:
    total_period: 3.943417800784257
  total_infectious:
    total_period: 5.139596285999966
tv_detection_b: 0.08702883001620004
tv_detection_c: 118.27727897299147
prop_detected_among_symptomatic: 0.045 # 0.14485229976709896
icu_prop: 0.2030763050384177
ifr_double_exp_model_params:
  k: 14.243326296932597
  last_representative_age: 82.83510422866601
compartment_periods:
  hospital_late: 12.670437110817831
  icu_late: 7.346817122522202

mixing:
  school:
    append: false
    times:
      - 2020-03-12
      - 2020-03-13
      - 2020-07-30
    values:
      - 1.0
      - 0.1
      - 0.1

# Mapping of Google Mobility locations to Autumn-specific locations
google_mobility_locations:
  work:
    - workplaces
  other_locations:
    # Parks not included
    - retail_and_recreation
    - grocery_and_pharmacy
    - transit_stations
