---
# When to introduce the scenario interventions taking off from the baseline
scenario_start_time: 85

# Parameters used to build a general model of COVID-19 disease for application to Australia or internationally
# MODEL STRUCTURE PARAMETERS

implement_importation: False
imported_cases_explict: False # whether to explicitely include imported cases
import_secondary_rate: 0.
data:
  times_imported_cases: []
  n_imported_cases: []

traveller_quarantine:
  times: [0.]
  values: [0.]

# Mean time (?) spent in each compartment
compartment_periods:
  hospital_early: 5.
  hospital_late: 8.
  icu_early: 5.
  icu_late: 10.

# Mean time (?) spent in each compartment, defined via proprotions
compartment_periods_calculated:
  total_infectious:
    total_period: 7.
    proportions:
      # Proportion of the infectious period spent in the early compartment (i.e. can't be isolated for symptoms), assumed
      infectious: 0.333
      late: 0.667

  incubation:
    total_period: 5.
    proportions:
      exposed: 0.5
      # Proportion of the exposed period spent infectious - i.e. "presymptomatic", assumed
      presympt: 0.5

# Stratification-related requests
stratify_by:
  - agegroup
  - clinical

# Currently must use only four strata, because deaths will not be calculated correctly otherwise - should be quickly
# adaptable to fewer strata as needed, though
clinical_strata:
  - non_sympt
  - sympt_non_hospital
  - sympt_isolate
  - hospital_non_icu
  - icu
agegroup_breaks:
  - 80
  - 5

# AGE-STRATIFIED PARAMETERS

# Infectiousness progression adjustments - in ten year brackets that need to be adapted to model strata later
# Extracted by WebPlotDigitizer from the LSHTM's "Age-dependent effects in the ..." Fig 2b, upper-left panel
symptomatic_props:
  - 0.396 # 0-9
  - 0.252 # 10-19
  - 0.367 # 20-29
  - 0.408 # 30-39
  - 0.476 # 40-49
  - 0.572 # 50-59
  - 0.710 # 60-69
  - 0.745 # 70+

# Proportion of symptomatic persons that are hospitalised - Verity et al.
hospital_props:
  - 0.001 # 0-9
  - 0.003 # 10-19
  - 0.012 # 20-29
  - 0.032 # 30-39
  - 0.049 # 40-49
  - 0.102 # 50-59
  - 0.166 # 60-69
  - 0.243 # 70-79
  - 0.273 # 80+

# Proportion of those hospitalised that are admitted to ICU - consistent with LSHTM's LMIC estimates parameters
icu_prop: 0.3

# Infection fatality proportions - Verity et al.
ifr_multiplier: 0
hospital_inflate: False
infection_fatality_props:
  - 0.00002 # 0-9
  - 0.00006 # 10-19
  - 0.0003 # 20-29
  - 0.0008 # 30-39
  - 0.0015 # 40-49
  - 0.006 # 50-59
  - 0.022 # 60-69
  - 0.051 # 70-79
  - 0.093 # 80+

# Reduced susceptibility in children - assumed, but informed by Iceland NEJM paper
young_reduced_susceptibility: 0.5
reduced_susceptibility_agegroups:
  - "0"
  - "5"
  - "10"
  - "15"

# NON-AGE-STRATIFIED PARAMETERS

# Adjust the infectiousness of clinical strata - assumed
non_sympt_infect_multiplier: 0.5
hospital_non_icu_infect_multiplier: 0.2
icu_infect_multiplier: 0.2

# parameters of tanh-based scale-up function used to define time-variant detection
tv_detection_b: .05 # shape parameter of the tanh-based curve
tv_detection_c: 90 # inflection point
tv_detection_sigma: 1. # height of the lower asymptote (1. means constant function)

# proportion of isolated cases among symptomatic
prop_detected_among_symptomatic: 0.6

# clinical proportions for imported cases
symptomatic_props_imported: .5
hospital_props_imported: .05
icu_prop_imported: .3
prop_detected_among_symptomatic_imported: .6

# parameters to define the effect (infectiousness adjustment) of self-isolation and enforced isolation
self_isolation_effect: .67
enforced_isolation_effect: 1.

# Country to extract Prem mixing matrix from
country: null

# Country to extract stratified population data from - should eventually use only one of country or iso3
iso3: null

# Initial conditions
infectious_seed: 10

# Running time-related - for COVID-19 model, all times are assumed to be in days and reference time is 1st Jan 2020
start_time: 40.
end_time: 350.
time_step: 1

# Base model definition
contact_rate: 0.03 # Expected to be calibrated for each application
icu_mortality_prop: 0.5

# Compulsory parameter that is completely overwritten in stratification, rather than being modified
infect_death: 0.

# Compulsory parameter for all models, even though there are no population-wide deaths
universal_death_rate: 0.

# Parameters relating to adjusting the mixing matrix to reflect interventions
mixing: {}
npi_effectiveness: {}
reinstall_regular_prayers: False
prayers_params:
  restart_time: 0
  prop_participating: 0.
  contact_multiplier: 1.
