iso3: ITA

#start_time: -20.
end_time: 190.
scenario_start_time: 182

infectious_seed: 200
use_verity_mortality_estimates: False

microdistancing:
  b: -0.05
  c: 119.95984134484922  # MLE
  sigma: 0.686649203624233 # MLE

# MLE estimates
contact_rate: 0.05921242814772146
start_time: 34.99932424353296
npi_effectiveness:
  other_locations: 0.8234345700664212
compartment_periods_calculated:
  incubation:
    total_period: 1.3800408943365559
  total_infectious:
    total_period: 2.7588914362847907
tv_detection_b: 0.05151334377773505
tv_detection_c: 99.33978104919737
prop_detected_among_symptomatic: 0.3151381661036723
icu_prop: 0.25979174008824807
ifr_double_exp_model_params:
  k: 12.022763863722314
  last_representative_age: 77.01173944854357
compartment_periods:
  hospital_late: 8.083038888664918
  icu_late: 15.045914509544176

mixing:
  school:
    append: false
    times:
      - 2020-03-18
      - 2020-03-20
      - 2020-06-27  # FIXME: update this time
    values:
      - 1.0
      - 0.1
      - 0.1

# Mapping of Google Mobility locations to Autumn-specific locations
google_mobility_locations:
  work:
    - workplaces
  other_locations:
    # Parks not included
    - retail_and_recreation
    - grocery_and_pharmacy
    - transit_stations
