iso3: FRA

#start_time: -20.
end_time: 190.
scenario_start_time: 182

infectious_seed: 200
use_verity_mortality_estimates: False

microdistancing:
  b: -0.05
  c: 97.51806786653714  # MLE
  sigma: 0.6371233869548765  # MLE

# MLE estimates
contact_rate: 0.05895522548480011
start_time: 39.76073024762635
npi_effectiveness:
  other_locations: 0.7392042852300448
compartment_periods_calculated:
  incubation:
    total_period: 2.269909881453525
  total_infectious:
    total_period: 3.5026021114149986
tv_detection_b: 0.08346042370648482
tv_detection_c: 89.88255843155197
prop_detected_among_symptomatic: 0.735363415044217
icu_prop: 0.4570305804031546
ifr_double_exp_model_params:
  k: 9.19723590488763
  last_representative_age: 77.45838682056137
compartment_periods:
  hospital_late: 5.559777532751516
  icu_late: 13.045362141421554

mixing:
  school:
    append: false
    times:
      - 2020-03-18
      - 2020-03-20
      - 2020-06-27  # FIXME: update this time
    values:
      - 1.0
      - 0.1
      - 0.1

# Mapping of Google Mobility locations to Autumn-specific locations
google_mobility_locations:
  work:
    - workplaces
  other_locations:
    # Parks not included
    - retail_and_recreation
    - grocery_and_pharmacy
    - transit_stations
