name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: pytest -W ignore -vv -m "not run_models and not calibrate_models"
  test_runs:
    needs: test_basic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: pytest -W ignore -vv -m run_models
  test_calibrations:
    needs: test_basic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: pytest -W ignore -vv -m calibrate_models
